<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="pragma" content="no-cache" />
<meta name="author" content="Ralph Garcia" />
<meta name="language" content="English" />
<meta name="charset" content="ISO-8859-1" />
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<meta name="Copyright" content="Copyright (c)2010 TriGeminalSolutions.com" />

<script language="javascript" src="global/js/jquery/jquery-1.4.1.min.js"></script>
<script type="text/javascript" src="global/js/global.js"></script>

<!-- Layout Resizer -->
<script type="text/javascript" src="global/js/jquery.layout.ui.js"></script>
<!-- AutoSuggest -->
<script type="text/javascript" src="global/js/dimensions.js"></script>
<script type="text/javascript" src="global/js/autosuggest.js"></script>
<!-- Meals Shuttle Controls -->
<script type="text/javascript" src="global/js/shuttle.js"></script>

<script type="text/javascript">
	$(document).ready(function () {
		$('body').layout({ applyDefaultStyles: true });
	});
	
	$(function(){
	    setAutoComplete("searchField", "results", "autocomplete.php?part=");
	});
	
</script>

<style type="text/css" media="screen">
	@import url("global/css/all.css");
</style>


