<?php

// Set the path that will be used in include files
define("path", "http://www.pencilmedia.com");

// Copyright Info
define("copyright", "&copy;" . date('Y') . " Pencil Media");

//Browser Titles
define("homeTitle", "Pencil Media : Design and Development");
define("workTitle", "Pencil Media : Work");
define("aboutTitle", "Pencil Media : About");
define("contactTitle", "Pencil Media : Contact");
define("uxTitle", "Pencil Media : User Experience Development");

//Page Headers
define("homeHead", "We design and build web stuff.");
define("workHead", "Work");
define("aboutHead", "About");
define("contactHead", "Contact");
define("archiveHead", "Work");

//SubPage Headers
define("webWork", "Web");
define("icoWork", "Icons");
define("mobiWork", "Mobile");
define("logoWork", "Logos");
define("sampWork", "HTML5 &amp; CSS3");


//UX Page Headers
define("uxHead", "UX Development Resource");

//UX MainNav Headers
define("uxd", "User Experience Development (UXD)");
define("fee", "Front-End Engineer");
define("ixd", "Interaction Design (IxD)");

//UX Subnav Menu
define("uxdName", "Web Development");
define("visualName", "Visual Design");
define("ixdName", "Interaction Design");
define("jsName", "JavaScript");
define("cssName", "CSS");
define("htmlName", "HTML");


//PM Labs Page Headers
define("labsHead", "Pencil Media Labs");

//PM Labs MainNav Menu
define("labsProj", "Projects");

//PM Labs Subnav Menu
define("labsName", "PM Projects");
define("allProjSubNav", "All Projects");
define("gitSubNav", "Repositories");


// URL PATHS
define("pathToWork", "http://www.pencilmedia.com/work/");
define("pathToAbout", "http://www.pencilmedia.com/about/");
define("pathToContact", "http://www.pencilmedia.com/contact/");

define("pathToWeb", "http://www.pencilmedia.com/work/");
define("pathToIcons", "http://www.pencilmedia.com/work/icons.php");
define("pathToMobile", "http://www.pencilmedia.com/work/mobile.php");

define("pathToUX", "http://www.pencilmedia.com/ux/");
define("pathToLabs", "http://labs.pencilmedia.com");

?> 