<?php
define("siteTitle", "SFPCU : Auto Buying Service");
define("processTitle", "SFPCU : Auto Buying Service : How It Works");

define("financeTitle", "SFPCU : Auto Buying Service : Auto Buying &amp; Leasing");
define("advantageTitle", "SFPCU : Auto Buying Service : Process");
define("processTitle", "SFPCU : Auto Buying Service :  How It Works");
define("testimonialsTitle", "SFPCU : Auto Buying Service : Testimonials");
define("tradeinTitle", "SFPCU : Auto Buying Service : Trade-ins");
define("testdriveTitle", "SFPCU : Auto Buying Service : Hassle Free Test Drives");
define("contactTitle", "SFPCU : Auto Buying Service : Contact Us");
define("inquiryTitle", "SFPCU : Auto Buying Service : Inquire About a Vehicle");
define("aboutTitle", "SFPCU : Auto Buying Service : About Us");
define("faqsTitle", "SFPCU : Auto Buying Service : FAQs");
define("privacyTitle", "SFPCU : Auto Buying Service : Privacy Policy");
define("inventoryTitle", "SFPCU : Auto Buying Service : Pre-Owned Inventory");

define("mainphone", "800.716.9550");
?>
