<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="pragma" content="no-cache" />

<meta name="author" content="Ralph Garcia" />
<meta name="copyright" content="Ralph A. Garcia of Pencil Media Design for PersonalAutoShopper.org" />
<meta name="language" content="English" />
<meta name="charset" content="ISO-8859-1" />
<meta name="MSSmartTagsPreventParsing" content="true" />
<meta name="distribution" content="Global" />
<meta name="rating" content="General" />
<meta name="expires" content="Never" />
<meta name="robots" content="Index, Follow" />
<meta name="robots" content="all" />
<meta name="revisit-after" content="30 Days" />
<meta name="Copyright" content="Copyright (c)1995-2010 PersonalAutoShopper.org" />

<meta name="description" content="PersonalAutoShopper.org: Auto buying service which can get you any make and any model vehicle for less, without the headache of a dealer." />
<meta name="keywords" content="Bay Area Auto, Bay Area Cars, Bay Area Vehicle Purchasing, Bay Area Auto Broker, Silicon Valley Cars, trade in, Auto Brokers, San Francisco auto brokers, Bay Area Auto Broker, Bay Area Car Dealers, Mercedes Benz car dealers, BMW car dealers, Porsche car dealers, Audi car dealers, Acura car dealer, Jaguar car dealers, Chevy car dealers, car Lexus dealers, car Cadillac dealers, Auto Buying Service, auto finance service, car leasing service, auto leasing service, bay area leasing,vehicle financing, msrp, car invoice pricing, auto sales, auto buying service, online auto broker service" />

<link rel="stylesheet" href="global/css/all.css" type="text/css" />

<!-- BEGIN: JQUERY -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
<!-- END: JQUERY -->
<script src="global/js/global.js" type="text/javascript"></script>
<script src="global/js/forms.js" type="text/javascript"></script>


