<?php

// Copyright Info
define("copyright", "&copy;" . date('Y') . " Pencil Media");

////////////////////////////////////////////////////////////////////////////////////////////////////////
// Browser Titles
////////////////////////////////////////////////////////////////////////////////////////////////////////

define("homeTitle", "Pencil Media Design and Development");
define("workTitle", "Work : Pencil Media");
define("aboutTitle", "About : Pencil Media");
define("contactTitle", "Contact : Pencil Media");
define("uxTitle", "User Experience Development : Pencil Media");


////////////////////////////////////////////////////////////////////////////////////////////////////////
// Headers
////////////////////////////////////////////////////////////////////////////////////////////////////////

//Page Headers
define("homeHead", "We design and build web stuff.");
define("workHead", "Work");
define("aboutHead", "About");
define("contactHead", "Contact");
define("archiveHead", "Work");

//SubPage Headers
define("webWork", "Web");
define("icoWork", "Icons");
define("mobiWork", "Mobile");
define("logoWork", "Logos");
define("sampWork", "HTML5 &amp; CSS3");

//UX Page Headers
define("uxHead", "UX Development Resource");

//UX MainNav Headers
define("uxd", "User Experience Development (UXD)");
define("fee", "Front-End Engineer");
define("ixd", "Interaction Design (IxD)");

//PM Labs Page Headers
define("labsHead", "Pencil Media Labs");

//PM Labs MainNav Menu
define("labsProj", "Projects");

//PM Labs Subnav Menu
define("labsName", "PM Projects");
define("allProjSubNav", "All Projects");
define("gitSubNav", "Repositories");


////////////////////////////////////////////////////////////////////////////////////////////////////////
// Navigation
////////////////////////////////////////////////////////////////////////////////////////////////////////

//UX Subnav Menu
define("uxdName", "Web Development");
define("visualName", "Visual Design");
define("ixdName", "Interaction Design");
define("jsName", "JavaScript");
define("cssName", "CSS");
define("htmlName", "HTML");


?> 