<?php
// Setup Website Titles
define("homeTitle", "TriGeminal Solutions &trade; Demo");


// Setup Page Nav Header
define("page1Header", "Page 1 Title : <span>Page 1 (Test)</span>");
define("page2Header", "Migraine Questionnaire: <span>Page 6 (Motion)</span>");
define("page3Header", "Migraine Questionnaire: <span>Page 4 (Lunch)</span>");
define("page4Header", "Page 4");
define("page5Header", "Barometric Pressure Change");


// Setup Footer Navigation
// Back Button
define("page1Back", "href=\"index.php\"");
define("page2Back", "href=\"index.php\"");
define("page3Back", "href=\"page2.php\"");
define("page4Back", "href=\"page3.php\"");
define("page5Back", "href=\"page4.php\"");
// Next Button
define("page1Next", "href=\"page2.php\"");
define("page2Next", "href=\"page3.php\"");
define("page3Next", "href=\"page4.php\"");
define("page4Next", "href=\"page5.php\"");
define("page5Next", "href=\"page5.php\"");




?> 